name: .NET

on:
  push:
    branches: [ "main", "controllers" ]
  pull_request:
    branches: [ "main", "controllers" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: List backend directory
      run: ls -la ./backend

    - name: Restore dependencies
      run: dotnet restore ./backend

    - name: Build
      run: dotnet build --configuration Release --no-restore ./backend

    - name: Test
      run: dotnet test --no-restore --verbosity normal ./backend
