name: .NET

on:
  push:
    branches: ["main", "controllers"]
  pull_request:
    branches: ["main", "controllers"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Check out the code from the repository

      - name: Setup .NET
        uses: actions/setup-dotnet@v4 # Set up the .NET SDK
        with:
          dotnet-version: 8.0.x # Specify the exact .NET SDK version

      - name: List backend directory
        run: ls -la ./backend # List contents of the backend directory to verify the structure

      - name: Create bin and obj directories
        run: mkdir -p ./backend/bin ./backend/obj # Ensure necessary directories are created

      - name: Restore dependencies
        run: dotnet restore ./backend # Restore project dependencies

      - name: Build
        run: dotnet build --configuration Release --no-restore ./backend # Build the project

      - name: Test
        run: dotnet test --no-restore --verbosity normal ./backend # Run tests
      - name: Deploy to server
        run: |
          # Example deployment steps
          # Copy files to the deployment directory
          cp -r ./backend/bin/Release/net8.0/* /home/datnt/datj-backend

          # Restart the application service (modify as needed)
          sudo systemctl restart datj-backend.service
        shell: bash
